### ISSUE TITLE
How to render messages in thymeleaf template

### ISSUE THREAD

**Issue by sergio11** [jeslopalo/flash-messages#8]
Hi,

How could I display messages in a Thymeleaf template?
Is there any way even though it is more manual ?.

I really like your library and it's a shame I can not use it because I'm using Thymeleaf.

greetings.

**Comment by jeslopalo** [comment]
Hi @sergio11 !

I am currently working on a new version (1.x).

There will be two main changes:
- will be **autoconfigurable** when used with **spring-boot**
- will be compatible with **thymeleaf** (dialect)

I don't know when I can have it (it's almost terminated but I can't spend much time now). If you can't wait for the new release, it shouldn't be difficult to integrate it manually (I'll confirm it as soon as I have a little time to dedicate it).

regards.

**Comment by sergio11** [comment]
Thanks, if I needed it soon, but I understand that you have little time. 
I will try to investigate how to do it manually. 

For now I will use version 0.2.4 that fits with the documentation.

greetings.

**Comment by sergio11** [comment]
excellent work!!
Could you give me an example of how to use it?
Is the current documentation valid for version 1.1?
I'm not using Spring boot.

thanks

**Comment by jeslopalo** [comment]
Hi @sergio11 and happy new year!

I hope you find the new version helpful. Now I have to improve the documentation, but that's another story...   **;)**

Meanwhile, you can take a look at [maven-spring-war-thymeleaf-showcase](https://github.com/jeslopalo/flash-messages-showcases/tree/master/maven-spring-war-thymeleaf-showcase). It's not intended as documentation but can serve you as a guide.

Don't hesitate to report any issues or suggestions.

Thanks for using flash-messages!

**Comment by sergio11** [comment]
Thanks and happy year to you too!.
When I get Flash on the controller, I get the following exception:

```
2017-01-07 13:31:29 ERROR ErrorController:42 - Exception during execution of SpringSecurity application
org.springframework.beans.BeanInstantiationException: Failed to instantiate [es.sandbox.ui.messages.Flash]: Specified class is an interface
org.springframework.beans.BeanInstantiationException: Failed to instantiate [es.sandbox.ui.messages.Flash]: Specified class is an interface
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:101)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:101)
	at org.springframework.web.method.annotation.ModelAttributeMethodProcessor.createAttribute(ModelAttributeMethodProcessor.java:142)
	at org.springframework.web.method.annotation.ModelAttributeMethodProcessor.createAttribute(ModelAttributeMethodProcessor.java:142)
	at org.springframework.web.servlet.mvc.method.annotation.ServletModelAttributeMethodProcessor.createAttribute(ServletModelAttributeMethodProcessor.java:80)
```

I followed the configuration of the example project, Here's the controller:

 ```
@PostMapping("/save")
    public String process(
            Flash flash,
            @ModelAttribute(ATTRIBUTE_NAME) @Valid Product product, 
            BindingResult bindingResult,
            @RequestParam(value = "continueEditing", required = false, defaultValue = "false") boolean continueEditing,
            RedirectAttributes model,
            // SessionStatus lets you clear your SessionAttributes
            SessionStatus sessionStatus,
            HttpServletRequest request){
        
        for(ProductLine line : product.getProductLines())
            line.setProduct(product);
        
        logger.info("Product to save: " + product.toString());
        if (bindingResult.hasErrors()) {
            model.addFlashAttribute(BINDING_RESULT_NAME, bindingResult);
            String referer = request.getHeader("Referer");
            return "redirect:"+referer;
        }
        
        productsRepository.save(product);
        sessionStatus.setComplete(); //remove product from session
        // add success flash message
        flash.success("message.product.save.success", product.getId());
        String redirectTo;
        if(continueEditing){
            model.addAttribute("productId", product.getId());
            redirectTo = "redirect:/admin/products/edit/{productId}";
        }else{
            redirectTo = "redirect:/admin/products/all";
        }
        return redirectTo; 
    }
```
I import the FlashMessageConfigurer as follows:

```
@Configuration
@EnableWebMvc
@Import(value = { FlashMessagesConfig.class, ViewConfig.class, i18nConfig.class })
@ComponentScan(value = "web")
public class WebConfig extends WebMvcConfigurerAdapter{}
```

As there is a lot of code I leave the link of the [project](https://github.com/sergio11/springmvc-webflow-ecommerce) in case you want to have a look.

thanks

**Comment by jeslopalo** [comment]
it seems like flash-messages has not been bootstrapped properly. 

Look if your FlashMessagesConfig is been loaded in the servlet's context (Maybe tracing a message in a default constructor).

**Comment by sergio11** [comment]
It seems that if I initialize, I get these messages by console:

```
2017-01-08 12:36:14 INFO  FlashMessagesConfig:18 - Init FlashMessagesConfig .......
2017-01-08 12:36:14 INFO  FlashMessagesConfigurationSupport:52 - Using application context: WebApplicationContext for namespace 'dispatcher-servlet': startup date [Sun Jan 08 12:36:12 CET 2017]; parent: Root WebApplicationContext
```

**Comment by sergio11** [comment]
I also still have a problem with the spring security argument resolver  for **@AuthenticationPrincipal**.

When I include @EnableFlashMessages, the user is empty.

When I asked to Spring Security people they told me:

> This issue is because DelegatingFlashMessagesConfiguration eagerly initializes the handlerExceptionResolver which prevents the AuthenticationPrincipalArgumentResolver from being registered until after Spring MVC has constructed the DispatcherServlets custom argument resolvers.

The  issue is [here](https://github.com/spring-projects/spring-security/issues/4155).

**Comment by jeslopalo** [comment]
Hi @sergio11 

as soon as I can spend some time, I will try to reproduce your situation to see if we can find a solution.

Spring does not allow you to easily configure a `HandlerMethodArgumentResolver` for **exception handlers**. As far as I remember flash-messages should not interfere with other configurations, but I have to check with the specific case of SpringSecurity.

I'm sorry that the integration of flash-messages is not being as transparent as it should be.
